version: "3"
services:
  users-api:
    build: ./
    environment: 
        DB_CONNECTION_URL: mongodb://mongo:27017
        APPLICATION_PORT: '3000'
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
